---
title: "Data"
author: "Andrea Bowling"
date: "10/21/2021"
output: html_document
---

```{r loading libraries}
library(robotstxt) # web scraping robots
library(tidyverse) # data manipulation
library(readtext) # read files
library(tidytext) # separate text
library(rvest) 
```


```{r installing packages}
pacman::p_load(robotstxt) #load/install 

paths_allowed(paths = "https://www.last.fm/") # check permissions
#> [1] TRUE
```
```{r read and parse html}
lyrics_url <- "https://www.last.fm/music"
html <- read_html(lyrics_url)  # read raw html and parse to xml
html
```


```{r targeting lyrics}
lyrics <- html %>%
    html_elements("p.lyrics-paragraph") %>%
    html_text()
lyrics
```
```{r targeting genre}
genre <- html %>%
    html_element("a.header-new-crumb") %>%
    html_text()
genre
```


```{r Get Lyrics}
get_lyrics <- function(lyrics_url) {
    # Function: Scrape last.fm lyrics page for: artist, song, and lyrics from a
    # provided content link.  Return as a tibble/data.frame

    cat("Scraping song lyrics from:", lyrics_url, "\n")

    pacman::p_load(tidyverse, rvest)  # install/ load package(s)

    url <- url(lyrics_url, "rb")  # open url connection 
    html <- read_html(url)  # read and parse html as an xml object
    close(url)  # close url connection

    artist <- html %>%
        html_element("a.header-new-crumb") %>%
        html_text()

    song <- html %>%
        html_element("h1.header-new-title") %>%
        html_text()

    lyrics <- html %>%
        html_elements("p.lyrics-paragraph") %>%
        html_text()

    genre <- html %>%
        html_elements("p.lyrics-paragraph") %>%
        html_text()
    
    cat("...one moment ")

    Sys.sleep(1)  # sleep for 1 second to reduce server load

    song_lyrics <- tibble(artist, song, lyrics, lyrics_url)

    cat("... done! \n")

    return(song_lyrics)
}
```


```{r}
write_content <- function(content, target_file) {
    # Function: Write the tibble content to disk. Create the directory if it
    # does not already exist.

    pacman::p_load(tidyverse)  # install/ load packages

    target_dir <- dirname(target_file)  # identify target file directory structure
    dir.create(path = target_dir, recursive = TRUE, showWarnings = FALSE)  # create directory
    write_csv(content, target_file)  # write csv file to target location

    cat("Content written to disk!\n")
}
```



```{r getting genre lyrics}
get_genre_lyrics_urls <- function(last_fm_genre) {
  # Function: Scrapes a given last.fm genre title for top tracks in
  # that genre and then creates links to the lyrics pages for these tracks
  
  cat("Scraping top songs from:", last_fm_genre, "genre: \n")
  
  pacman::p_load(tidyverse, rvest) # install/ load packages
  
  # create web url for the genre listing page
  genre_listing_url <- 
    paste0("https://www.last.fm/tag/", last_fm_genre, "/tracks") 
  
  genre_lyrics_urls <- 
    read_html(genre_listing_url) %>% # read raw html and parse to xml
    html_elements("td.chartlist-name a") %>% # isolate the track elements
    html_attr("href") %>% # extract the href attribute
    paste0("https://www.last.fm", ., "/+lyrics") # join the domain, relative artist path, and the post-pended /+lyrics to create an absolute URL
  
  return(genre_lyrics_urls)
}
```


```{r hip hop}
get_genre_lyrics_urls("hip+hop") %>%  # get urls for top hip hop tracks
  head(n = 10) # only display 10 tracks
```

```{r hip hop titles into lyrics}
get_genre_lyrics_urls("hip+hop") %>% # get lyrics urls for specific genre
  map(get_lyrics) %>%  # scrape lyrics url
  bind_rows() %>% # combine tibbles into one
  write_content(target_file = "../data/original/lastfm/hip_hop.csv") # write to disk
```

