---
title: "Acquire data"
date: "`r Sys.Date()`"
bibliography: references.bib
biblio-style: apalike
---

## About

### Description

<!-- The aim of this script -->

JF: make sure to add prose description to document your processing steps and their results!

### Usage

<!-- How to run this script: what input it requires and output produced -->

## Setup

```{r setup}
# Script-specific options or packages
library(robotstxt) # web scraping robots
library(tidyverse) # data manipulation
library(readtext) # read files
library(tidytext) # separate text
library(rvest) 


paths_allowed(paths = "https://www.last.fm/") # check permissions
#> [1] TRUE
source("../functions/acquire_data_functions.R")
```

## Run

<!-- Steps involved in acquiring and organizing the original data -->

```{r get-lyrics}
download_lastfm_lyrics(last_fm_genre = "rock", target_file = "../data/original/lastfm/rock_lyrics.csv")


download_lastfm_lyrics(last_fm_genre = "hip-hop", target_file = "../data/original/lastfm/hip-hop_lyrics.csv")

download_lastfm_lyrics(last_fm_genre = "pop", target_file = "../data/original/lastfm/pop_lyrics.csv")

download_lastfm_lyrics(last_fm_genre = "country", target_file = "../data/original/lastfm/country_lyrics.csv")
```

JF: make sure to document the data that you have acquired and added to the `../data/original/lastfm/` directory.


## Finalize

### Log

<!-- Any description that will be helpful to understand the results of this script and how it contributes to the aims of the project -->

### Session

<details><summary>View session information</summary>

```{r, child="_session-info.Rmd"}
```

</details>

```{r cleanup, echo=FALSE}
rm(list = ls()) # clean working environment
```

## References
