---
title: "Transform dataset"
date: "`r Sys.Date()`"
bibliography: references.bib
biblio-style: apalike
---

## About

### Description

<!-- The aim of this script -->

### Usage

<!-- How to run this script: what input it requires and output produced -->

## Setup

```{r setup}
paths_allowed(paths = "https://www.last.fm/") # check permissions
#> [1] TRUE
source("../functions/acquire_data_functions.R")
```

## Run

```{r Read}
lastfm <- read_csv(file = "../data/derived/lastfm/lastfm_curated.csv")  # read in lastfm_curated dataset

lastfm <- 
  lastfm %>% # dataset
  mutate(lyrics = 
           str_replace_all(string = lyrics, 
                           pattern = "([a-z'!,.)?I])([A-Z])", # find contiguous end/ new line segments
                           replacement = "\\1 \\2")) %>%  # replace with whitespace between
  mutate(lyrics = str_remove_all(lyrics, "\\(.+?,\\)")) # remove backing vocals (Take On Me)
lastfm %>% # dataset
 mutate(lyrics = str_replace_all(string = lyrics, 
                                    pattern = "'\\ss", 
                                    replacement = "'s")) # replace ' s with `s

```


```{r}
lastfm %>% # curated dataset
  slice_head(n = 5) %>% # first 5 observations
  knitr::kable(booktabs = TRUE, # print pretty table
               captions = "Sample lyrics from curated Last.fm dataset.") # add caption to the table
```

## Finalize

### Log

<!-- Any description that will be helpful to understand the results of this script and how it contributes to the aims of the project -->

### Session

<details><summary>View session information</summary>

```{r, child="_session-info.Rmd"}
```

</details>

```{r cleanup, echo=FALSE}
rm(list = ls()) # clean working environment
```

## References
